Localstream
avinash240/pusher pull request #1
Opened 2021-07-12 18:57 UTC by wcgwink

Implements local file streaming to streamingdata channel

2021-07-12 23:27 UTC, avinash240 requested changes

2021-07-12 23:27 UTC, avinash240 commented on internal/streaming/local.go
> +	if la.Location == "" {
Why check for Location if it's not being used.

2021-07-12 23:27 UTC, avinash240 commented on internal/streaming/local.go
> +	fh, err := os.Open(path)
Shouldn't this be handling a directory instead of a single file?

2021-07-12 23:27 UTC, avinash240 commented on internal/streaming/local.go
> +			buffer = append(buffer, 0)[:len(buffer)]
This seems  a lot more complicated than it needs to be.   Why the append?

2021-07-12 23:27 UTC, avinash240 commented on internal/streaming/local.go
> +		n, err := f.Read(buffer[len(buffer):cap(buffer)])
We'll discuss this on Thursday.  I'm not sure why we need cap()

2021-07-16 21:53 UTC, wcgwink commented on internal/streaming/local.go
> +	fh, err := os.Open(path)
originally wasn't sure how we would handle the "songs" or audio sources. The pseudo code on the first meet showed Type Song and Type Playlist. I revamped to be a directory walk and when a directory is specified, or if a specific file is supplied it will bypass the walk.

2021-07-16 21:53 UTC, wcgwink commented on internal/streaming/local.go
> +	if la.Location == "" {
Future planning? Removed in revision. :)

2021-07-16 21:54 UTC, wcgwink commented on internal/streaming/local.go
> +			buffer = append(buffer, 0)[:len(buffer)]
Was used from the ReadAll function. I changed it to use the same buffer with no appends in the revision.

2021-07-16 21:55 UTC, wcgwink commented on internal/streaming/local.go
> +		n, err := f.Read(buffer[len(buffer):cap(buffer)])
removed

2021-07-19 18:45 UTC, avinash240 requested changes

2021-07-19 18:45 UTC, avinash240 commented on internal/streaming/local.go
> +			_ = n
Leftover debug?

2021-07-19 18:45 UTC, avinash240 commented on internal/streaming/local.go
> +			sd <- StreamingData{Bytes: buffer[:n]}
this won't work because the underlying slice is being changed by the next Read, you'll need to copy this before you send it.

2021-07-22 21:20 UTC, wcgwink commented on internal/streaming/local.go
> +			_ = n
yeah, fixed

2021-07-22 21:22 UTC, wcgwink commented on internal/streaming/local.go
> +	if !fS.IsDir() {
this is only for a path passed to the call, if it is a directory it will walk it, if not then it uses it as a file.

2021-07-26 23:20 UTC, wcgwink commented on internal/streaming/local.go
> +			sd <- StreamingData{Bytes: buffer[:n]}
fixed with a copy in latest revision

2021-07-26 23:20 UTC, wcgwink commented on internal/streaming/local.go
> +	if !fS.IsDir() {
fixed: checked if it is a regular file

2021-07-30 19:55 UTC, merged